In [1]:
import numpy as np
import abm2
%load_ext autoreload
%autoreload 2

rng = np.random.RandomState(40)

In [2]:
num_employees = 500
employee_list = [abm2.Employee(x=np.array([1.0, 12.0 + 3.0 * rng.normal(), 
                                           40.0 + 10.0 * rng.normal()]),
                               alpha=np.array([0.05]))
                 for i in range(num_employees)]
er0 = abm2.Employer(offer=lambda x, y: np.array([12.0]),
                    w=np.array([12.0]), beta=np.array([0.0, 0.0, 0.0])) # Unemployment
er1 = abm2.Employer(offer=lambda x, y: x.w + 1.2 * y.x[1],
                    w=np.array([42.0]), beta=np.array([-9.0, 0.2, 0.2]))
er2 = abm2.Employer(offer=lambda x, y: x.w + 1.4 * y.x[1],
                    w=np.array([23.0]), beta=np.array([-10.0, 0.1, 0.2]))
er3 = abm2.Employer(offer=lambda x, y: x.w + 0.2 * y.x[1],
                    w=np.array([32.0]), beta=np.array([-5.0, 0.5, -0.05]))
employer_list = [er0, er1, er2, er3]

In [3]:
my_model = abm2.Model(employer_list, employee_list)
alpha, beta, ww, xx, jobs, job_utilities, choice, true_opp, obs_opp = my_model.matching_process()

In [4]:
np.save("ww.npy", ww)
np.save("xx.npy", xx)
np.save("jobs.npy", np.squeeze(jobs))
np.save("obs_opp.npy", obs_opp)
np.save("true_opp.npy", true_opp)
np.save("choice.npy", choice)
np.save("job_utilities.npy", job_utilities)

In [5]:
true_opp

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.]])

In [6]:
obs_opp

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0.,  1.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.]])

In [7]:
np.squeeze(jobs)

array([[ 12.        ,  54.21282829,  37.24829967,  34.03547138],
       [ 12.        ,  53.93541711,  36.92465329,  33.98923618],
       [ 12.        ,  49.76015628,  32.05351566,  33.29335938],
       ..., 
       [ 12.        ,  57.5655252 ,  41.1597794 ,  34.5942542 ],
       [ 12.        ,  59.71293265,  43.6650881 ,  34.95215544],
       [ 12.        ,  60.346907  ,  44.40472483,  35.05781783]])